const API_BASE_URL='https://world-cup-api-proxy.zhanghao19900118.workers.dev';
const countryCodes={Algeria:'dz',Argentina:'ar',Australia:'au',Austria:'at',Belgium:'be','Bosnia and Herzegovina':'ba',Brazil:'br',Canada:'ca','Cape Verde':'cv',Colombia:'co',Croatia:'hr','Curaçao':'cw','Czech Republic':'cz','Democratic Republic of the Congo':'cd',Ecuador:'ec',Egypt:'eg',England:'gb-eng',France:'fr',Germany:'de',Ghana:'gh',Haiti:'ht',Iran:'ir',Iraq:'iq','Ivory Coast':'ci',Japan:'jp',Jordan:'jo',Mexico:'mx',Morocco:'ma',Netherlands:'nl','New Zealand':'nz',Norway:'no',Panama:'pa',Paraguay:'py',Portugal:'pt',Qatar:'qa','Saudi Arabia':'sa',Scotland:'gb-sct',Senegal:'sn','South Africa':'za','South Korea':'kr',Spain:'es',Sweden:'se',Switzerland:'ch',Tunisia:'tn',Turkey:'tr','United States':'us',Uruguay:'uy',Uzbekistan:'uz'};
const stageNames={R32:'32 强',R16:'16 强',QF:'四分之一决赛',SF:'半决赛','3RD':'季军赛',FINAL:'决赛'};
let matches=[];
let players=[];
let interactions=[];
let activeView='groups';
const app=document.querySelector('#app');

function escapeHTML(value=''){return String(value).replace(/[&<>'"]/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[char]))}
function flag(team){const code=countryCodes[team];if(!code)return '<span class="flag-placeholder">◌</span>';const regional={'gb-eng':'🏴','gb-sct':'🏴'};const emoji=regional[code]||code.toUpperCase().replace(/[A-Z]/g,c=>String.fromCodePoint(127397+c.charCodeAt(0)));return `<span class="flag-emoji" role="img" aria-label="${escapeHTML(team)} 国旗">${emoji}</span>`}
function scoreParts(m){return m.score&&m.score!=='—'?m.score.split('–'):['','']}
function isGroup(m){return /^[A-L]$/.test(m.group)}
function isKnockout(m){return !isGroup(m)}
function goMatch(id){location.hash=`/matches/${encodeURIComponent(id)}`}
function setHashView(view){location.hash=`/world-cup/${view}`}
function matchCard(m,compact=false){const [homeScore,awayScore]=scoreParts(m);return `<article class="match-card ${compact?'compact':''}" tabindex="0" role="link" onclick="goMatch('${escapeHTML(m.id)}')" onkeydown="if(event.key==='Enter')goMatch('${escapeHTML(m.id)}')"><div class="match-top"><span>${escapeHTML(stageNames[m.group]||`第 ${m.group} 组`)} · ${escapeHTML(m.date)}</span><span class="status ${m.status==='未开始'?'upcoming':''}">${escapeHTML(m.status)}</span></div><div class="team-line"><span class="flag">${flag(m.home)}</span><span>${escapeHTML(m.home)}</span><b class="score">${homeScore}</b></div><div class="team-line"><span class="flag">${flag(m.away)}</span><span>${escapeHTML(m.away)}</span><b class="score">${awayScore}</b></div><div class="match-foot"><span>${escapeHTML(m.time)} EDT</span><span>${escapeHTML(m.venue)} →</span></div></article>`}
function emptyState(text){return `<div class="empty-state">${escapeHTML(text)}</div>`}

function hero(){return `<section class="hero v2-hero"><div class="eyebrow">FIFA WORLD CUP 2026 · DG ARCHIVE</div><h1>2026 DG<br><em>世界杯全纪录</em></h1><div class="hero-meta"><span><strong>48</strong> 支球队</span><span><strong>104</strong> 场比赛</span><span><strong>16</strong> 座主办城市</span><span>完整赛程 · 比分 · 晋级路线</span></div></section>`}
function controls(){return `<div class="control-row v2-controls"><div class="segmented main-tabs" role="tablist"><button data-view="bracket" class="${activeView==='bracket'?'active':''}">淘汰赛</button><button data-view="groups" class="${activeView==='groups'?'active':''}">小组赛</button><button data-view="all" class="${activeView==='all'?'active':''}">全部赛程</button><button data-view="interactions" class="${activeView==='interactions'?'active':''}">互动记录</button></div><div class="filters"><label>数据源 <select class="select" id="sourceSelect"><option value="manual">手动（matches.json）</option><option value="football_api">football_api（2022）</option></select></label></div></div>`}
function groupView(){const groups='ABCDEFGHIJKL'.split('');return `<section class="view-panel"><div class="section-title"><div><span class="kicker">GROUP STAGE</span><h2>小组赛</h2></div><span>选择分组查看比赛与积分情况</span></div><div class="group-pills">${groups.map((g,i)=>`<button data-group="${g}" class="${i===0?'active':''}">${g} 组</button>`).join('')}</div><div id="groupPanel">${renderGroup('A')}</div></section>`}
function standings(list){const map={};const ensure=t=>map[t]||(map[t]={team:t,p:0,w:0,d:0,l:0,gf:0,ga:0,pts:0});list.forEach(m=>{if(m.score==='—')return;const [h,a]=m.score.split('–').map(Number);if(!Number.isFinite(h)||!Number.isFinite(a))return;const home=ensure(m.home),away=ensure(m.away);home.p++;away.p++;home.gf+=h;home.ga+=a;away.gf+=a;away.ga+=h;if(h>a){home.w++;home.pts+=3;away.l++}else if(h<a){away.w++;away.pts+=3;home.l++}else{home.d++;away.d++;home.pts++;away.pts++}});return Object.values(map).sort((a,b)=>b.pts-a.pts||(b.gf-b.ga)-(a.gf-a.ga)||b.gf-a.gf)}
function standingsTable(list){const rows=standings(list);return `<div class="standings"><h3>小组积分</h3><div class="standing-head"><span>#</span><span>球队</span><span>赛</span><span>净胜</span><span>积分</span></div>${rows.map((r,i)=>`<div class="standing-row ${i<2?'qualified':''}"><span>${i+1}</span><span>${flag(r.team)} ${escapeHTML(r.team)}</span><span>${r.p}</span><span>${r.gf-r.ga>0?'+':''}${r.gf-r.ga}</span><strong>${r.pts}</strong></div>`).join('')}</div>`}
function renderGroup(group){const list=matches.filter(m=>m.group===group);const teams=[...new Set(list.flatMap(m=>[m.home,m.away]))];return `<div class="group-heading"><div><small>GROUP ${group}</small><h3>${group} 组比赛</h3></div><div class="group-team-list">${teams.map(t=>`<span>${flag(t)} ${escapeHTML(t)}</span>`).join('')}</div></div><div class="group-layout">${standingsTable(list)}<div class="match-grid group-match-grid">${list.map(m=>matchCard(m,true)).join('')||emptyState('该分组暂无数据')}</div></div>`}
function bracketGame(m){const [a,b]=scoreParts(m);return `<button class="tree-match" onclick="goMatch('${escapeHTML(m.id)}')"><small>${escapeHTML(m.date)} · ${escapeHTML(m.time)}</small><span>${flag(m.home)} ${escapeHTML(m.home)} <b>${a}</b></span><span>${flag(m.away)} ${escapeHTML(m.away)} <b>${b}</b></span></button>`}
function roundColumn(stage,title,side){const all=matches.filter(m=>m.group===stage),half=Math.ceil(all.length/2);const games=side==='left'?all.slice(0,half):side==='right'?all.slice(half):all;return `<section class="tree-round" data-stage="${stage}" data-side="${side||'center'}"><h3>${title}</h3><div class="tree-games">${games.map(bracketGame).join('')||emptyState('暂无数据')}</div></section>`}
function trophy(){return `<div class="trophy-core" aria-label="DG Outright Cup"><span class="trophy-kicker">2026 DG</span><svg class="world-trophy" viewBox="0 0 150 240" role="img" aria-label="金色世界杯奖杯"><defs><linearGradient id="gold" x1="0" x2="1"><stop stop-color="#8f641c"/><stop offset=".25" stop-color="#ffe08a"/><stop offset=".52" stop-color="#ba801d"/><stop offset=".78" stop-color="#fff0ac"/><stop offset="1" stop-color="#835817"/></linearGradient></defs><circle cx="75" cy="46" r="34" fill="url(#gold)"/><path d="M52 35c9-11 19-15 31-12 8 2 16 8 20 17-14-2-26 2-34 12-7-7-12-12-17-17Zm-11 29c10 11 24 17 39 16 13-1 23-6 31-16-4 24-17 39-36 48C56 103 44 87 41 64Z" fill="#2d5e49" opacity=".9"/><path d="M48 78c-6 32-1 59 16 81h22c17-22 22-49 16-81-6 9-15 17-27 23-12-6-21-14-27-23Z" fill="url(#gold)"/><path d="M61 151h28l9 32H52l9-32Zm-17 32h62v20H44z" fill="url(#gold)"/><path d="M35 205h80l9 23H26l9-23Z" fill="url(#gold)"/></svg><strong>OUTRIGHT CUP</strong><span class="trophy-sub">THE ROAD TO GLORY</span><div class="outright-mark"><i></i><b>DG</b><i></i></div></div>`}
function bracketView(){return `<section class="view-panel"><div class="section-title"><div><span class="kicker">KNOCKOUT STAGE</span><h2>32 强最终落位图</h2></div><div class="zoom-controls"><button id="fitTree">适应屏幕</button><button id="zoomOut">−</button><button id="zoomIn">＋</button></div></div><div class="bracket-stage" id="bracketStage"><div class="symmetric-tree" id="symmetricTree"><svg class="bracket-lines" id="bracketLines" aria-hidden="true"></svg><div class="tree-side left">${roundColumn('R32','1 / 16','left')}${roundColumn('R16','1 / 8','left')}${roundColumn('QF','1 / 4','left')}${roundColumn('SF','1 / 2','left')}</div>${trophy()}<div class="tree-side right">${roundColumn('SF','1 / 2','right')}${roundColumn('QF','1 / 4','right')}${roundColumn('R16','1 / 8','right')}${roundColumn('R32','1 / 16','right')}</div><div class="final-strip">${roundColumn('3RD','季军赛')}${roundColumn('FINAL','决赛')}</div></div></div></section>`}
function drawBracketLines(){const tree=document.querySelector('#symmetricTree'),svg=document.querySelector('#bracketLines');if(!tree||!svg)return;const box=tree.getBoundingClientRect();svg.setAttribute('viewBox',`0 0 ${tree.offsetWidth} ${tree.offsetHeight}`);svg.setAttribute('width',tree.offsetWidth);svg.setAttribute('height',tree.offsetHeight);const connect=(from,to)=>{const a=[...document.querySelectorAll(`[data-side="${from.side}"][data-stage="${from.stage}"] .tree-match`)],b=[...document.querySelectorAll(`[data-side="${to.side}"][data-stage="${to.stage}"] .tree-match`)];a.forEach((card,i)=>{const target=b[Math.floor(i/2)];if(!target)return;const ar=card.getBoundingClientRect(),br=target.getBoundingClientRect(),left=from.side==='left';const x1=(left?ar.right:ar.left)-box.left,x2=(left?br.left:br.right)-box.left,y1=ar.top+ar.height/2-box.top,y2=br.top+br.height/2-box.top,mid=(x1+x2)/2;const path=document.createElementNS('http://www.w3.org/2000/svg','path');path.setAttribute('d',`M${x1},${y1} H${mid} V${y2} H${x2}`);svg.appendChild(path)})};svg.innerHTML='';['left','right'].forEach(side=>{connect({side,stage:'R32'},{side,stage:'R16'});connect({side,stage:'R16'},{side,stage:'QF'});connect({side,stage:'QF'},{side,stage:'SF'})})}
function allView(){const dates=[...new Set(matches.map(m=>m.date))].sort();return `<section class="view-panel"><div class="section-title"><div><span class="kicker">FULL SCHEDULE</span><h2>全部赛程</h2></div><span>共 ${matches.length} 场</span></div><div class="schedule-filters"><select class="select" id="dateFilter"><option value="all">全部日期</option>${dates.map(d=>`<option>${d}</option>`).join('')}</select><select class="select" id="stageFilter"><option value="all">全部阶段</option><option value="groups">小组赛</option><option value="knockout">淘汰赛</option></select><input class="select search-input" id="teamFilter" placeholder="搜索球队"></div><div class="match-grid" id="allGrid">${matches.map(m=>matchCard(m)).join('')}</div></section>`}
function interactionsView(){const profiles=[...new Set(interactions.map(r=>r.profile_id))].sort();return `<section class="view-panel interaction-landing"><div class="section-title"><div><span class="kicker">PREDICTION RECORDS</span><h2>互动记录</h2></div><span>选择用户查看全部世界杯积分竞猜记录</span></div><div class="viewer-selector"><div class="selector-copy"><span class="profile-avatar large">DG</span><div><h3>选择 Viewer</h3><p>确认后进入该用户的完整记录、积分汇总和预测准确率页面。</p></div></div><div class="selector-actions"><select class="select" id="viewerSelect"><option value="">请选择 Viewer</option>${profiles.map(id=>`<option value="${escapeHTML(id)}">${escapeHTML(id)} · ${interactions.filter(r=>r.profile_id===id).length} 条</option>`).join('')}</select><button class="primary-btn" id="openViewer">查看全部记录</button></div><p class="selector-error" id="viewerError"></p></div><div class="viewer-preview-grid">${profiles.map(id=>{const rows=interactions.filter(r=>r.profile_id===id),correct=rows.filter(r=>r.result==='correct').length,current=Math.round(rows.at(-1)?.total_points||0);return `<article><span class="profile-avatar">${escapeHTML(id.slice(-2))}</span><div><h3>${escapeHTML(id)}</h3><p>${rows.length} 条记录 · ${correct} 次正确 · ${current} 积分</p></div><a href="#/profiles/${encodeURIComponent(id)}">查看 →</a></article>`}).join('')}</div><div class="probability-note"><strong>预测置信度说明</strong><span>根据竞猜权重分档折算：20%、40%、60%、80%或100%；不使用原表中大于1的倍率型数值。</span></div></section>`}
function viewHTML(){return activeView==='bracket'?bracketView():activeView==='all'?allView():activeView==='interactions'?interactionsView():groupView()}
function home(){app.innerHTML=`${hero()}<div class="container">${controls()}<div id="mainView">${viewHTML()}</div><div class="data-note"><span id="dataSource">数据源：手动（data/matches.json）</span><span id="updatedAt">最后更新：${escapeHTML(matches[0]?.last_updated||'—')}</span></div></div>`;bindHome()}

function bindHome(){document.querySelectorAll('[data-view]').forEach(btn=>btn.onclick=()=>setHashView(btn.dataset.view));document.querySelector('#sourceSelect').onchange=e=>e.target.value==='football_api'?loadApiData():loadStoredData(true);bindCurrentView()}
function bindCurrentView(){document.querySelectorAll('[data-group]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-group]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#groupPanel').innerHTML=renderGroup(btn.dataset.group)});const date=document.querySelector('#dateFilter'),stage=document.querySelector('#stageFilter'),team=document.querySelector('#teamFilter');if(date&&stage&&team){const filter=()=>{const query=team.value.trim().toLowerCase();const result=matches.filter(m=>(date.value==='all'||m.date===date.value)&&(stage.value==='all'||(stage.value==='groups'?isGroup(m):isKnockout(m)))&&(!query||m.home.toLowerCase().includes(query)||m.away.toLowerCase().includes(query)));document.querySelector('#allGrid').innerHTML=result.map(m=>matchCard(m)).join('')||emptyState('没有符合条件的比赛')};date.onchange=filter;stage.onchange=filter;team.oninput=filter}const viewer=document.querySelector('#viewerSelect'),openViewer=document.querySelector('#openViewer');if(viewer&&openViewer)openViewer.onclick=()=>{if(!viewer.value){document.querySelector('#viewerError').textContent='请先选择一个 Viewer';return}location.hash=`/profiles/${encodeURIComponent(viewer.value)}`};let zoom=1;const tree=document.querySelector('#symmetricTree');if(tree){requestAnimationFrame(drawBracketLines);document.querySelector('#zoomIn').onclick=()=>{zoom=Math.min(1.25,zoom+.1);tree.style.transform=`scale(${zoom})`};document.querySelector('#zoomOut').onclick=()=>{zoom=Math.max(.6,zoom-.1);tree.style.transform=`scale(${zoom})`};document.querySelector('#fitTree').onclick=()=>{zoom=.72;tree.style.transform=`scale(${zoom})`}}}

function initials(name){return name.split(/\s+/).map(x=>x[0]).slice(0,2).join('').toUpperCase()}
function playerCard(player){const source=player.source_url?`<a href="${escapeHTML(player.source_url)}" target="_blank" rel="noopener">资料来源 ↗</a>`:'';return `<article class="player-profile"><div class="player-photo"><img src="${escapeHTML(player.photo_url||'')}" alt="${escapeHTML(player.name)} 官方头像" loading="lazy" onerror="this.hidden=true;this.nextElementSibling.hidden=false"><span ${player.photo_url?'hidden':''}>${initials(player.name)}</span></div><div><small>${escapeHTML(player.position||'国家队球员')}</small><h3>${escapeHTML(player.name)}</h3><p>${escapeHTML(player.team||'')} · ${escapeHTML(player.number?`#${player.number}`:'')}</p>${source}</div></article>`}
function overviewTab(m){return `<div class="overview-grid"><article class="overview-card"><span>比赛阶段</span><strong>${escapeHTML(stageNames[m.group]||`${m.group} 组`)}</strong></article><article class="overview-card"><span>比赛状态</span><strong>${escapeHTML(m.status)}</strong></article><article class="overview-card"><span>比赛时间</span><strong>${escapeHTML(m.date)} ${escapeHTML(m.time)} EDT</strong></article><article class="overview-card"><span>比赛场馆</span><strong>${escapeHTML(m.venue)}</strong></article></div>`}
function playersTab(m){const relevant=players.filter(p=>p.team===m.home||p.team===m.away);return `<div class="section-title"><h2>球员表现</h2><span>头像来自资料供应方；失败时自动显示姓名缩写</span></div><div class="player-grid">${relevant.map(playerCard).join('')||emptyState('当前数据源尚未提供本场球员名单与官方头像')}</div>`}
function interactionResultLabel(value){return value==='correct'?'预测正确':value==='incorrect'?'预测未中':'待确认'}
function interactionRows(records){return `<div class="interaction-table-head"><span>日期 / 用户</span><span>比赛 / 比分</span><span>赛前预测</span><span>权重</span><span>置信度</span><span>结果</span><span>单场积分</span><span>累计积分</span></div>${records.map(r=>`<article class="interaction-row"><div><small>${escapeHTML(r.created_at||'日期待确认')}</small><a class="profile-link" href="#/profiles/${encodeURIComponent(r.profile_id)}"><span class="profile-avatar">${escapeHTML(r.profile_id.slice(-2))}</span><strong>${escapeHTML(r.profile_id)}</strong></a></div><div><b>${escapeHTML(r.game||'赛事互动记录')}</b><small>${escapeHTML(r.score||'比分待确认')}</small></div><div><b>${escapeHTML(r.prediction)}</b>${r.supported_team?`<small>${flag(r.supported_team)} ${escapeHTML(r.supported_team)}</small>`:''}</div><strong class="confidence-level">${r.weight??'—'}</strong><strong class="confidence-percent">${r.confidence_percent??'—'}%</strong><span class="prediction-result ${escapeHTML(r.result)}">${interactionResultLabel(r.result)}</span><strong class="points-change ${r.points_change>0?'positive':r.points_change<0?'negative':''}">${r.points_change>0?'+':''}${Math.round(r.points_change)}</strong><strong>${Math.round(r.total_points)}</strong></article>`).join('')}`}
function interactionTab(m){const records=interactions.filter(r=>r.match_ids.includes(m.id));const profiles=new Set(records.map(r=>r.profile_id)).size,correct=records.filter(r=>r.result==='correct').length,change=Math.round(records.reduce((sum,r)=>sum+(r.points_change||0),0));return `<div class="section-title"><div><span class="kicker">ANONYMOUS ACTIVITY</span><h2>匿名赛事互动记录</h2></div><span>世界杯积分竞猜演示数据</span></div><div class="interaction-summary"><div><span>相关记录</span><strong>${records.length}</strong></div><div><span>匿名用户</span><strong>${profiles}</strong></div><div><span>预测正确</span><strong>${correct}</strong></div><div><span>积分变化合计</span><strong>${change>0?'+':''}${change}</strong></div></div><div class="interaction-list">${records.length?interactionRows(records):emptyState('本场比赛暂无互动样本')}</div>`}
function detail(id){const m=matches.find(x=>x.id===id);if(!m){app.innerHTML=emptyState('找不到该比赛');return}const [a,b]=scoreParts(m);app.innerHTML=`<section class="detail-hero"><a class="back-link" href="#/world-cup/${activeView}">← 返回赛程</a><div class="versus"><div class="team-head"><span class="big-flag">${flag(m.home)}</span><h1>${escapeHTML(m.home)}</h1></div><div class="match-center"><strong>${a||'VS'}${a?' : ':''}${b||''}</strong><span>${escapeHTML(m.status)}</span></div><div class="team-head"><span class="big-flag">${flag(m.away)}</span><h1>${escapeHTML(m.away)}</h1></div></div><div class="detail-meta"><span>${escapeHTML(m.date)} · ${escapeHTML(m.time)} EDT</span><span>${escapeHTML(stageNames[m.group]||`${m.group} 组`)}</span><span>${escapeHTML(m.venue)}</span></div></section><div class="container"><div class="detail-tabs"><button class="active" data-detail="overview">比赛概览</button><button data-detail="players">球员表现</button><button data-detail="interactions">互动记录</button></div><div id="detailPanel">${overviewTab(m)}</div></div>`;document.querySelectorAll('[data-detail]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-detail]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');document.querySelector('#detailPanel').innerHTML=btn.dataset.detail==='players'?playersTab(m):btn.dataset.detail==='interactions'?interactionTab(m):overviewTab(m)})}

function profilePage(id){const records=interactions.filter(r=>r.profile_id===id),correct=records.filter(r=>r.result==='correct').length,finished=records.filter(r=>r.result!=='pending').length,rate=finished?Math.round(correct/finished*100):0,current=Math.round(records.at(-1)?.total_points??100);const matchName=record=>record.match_ids.map(mid=>{const m=matches.find(x=>x.id===mid);return m?`${m.home} vs ${m.away}`:mid}).join('、')||'未关联具体场次';app.innerHTML=`<section class="profile-hero"><a class="back-link" href="#/world-cup/interactions">← 返回互动记录</a><div class="profile-identity"><span class="profile-avatar large">${escapeHTML(id.slice(-2))}</span><div><span class="kicker">PREDICTION PROFILE</span><h1>${escapeHTML(id)}</h1><p>世界杯积分竞猜历史档案</p></div></div></section><div class="container"><div class="interaction-summary profile-summary"><div><span>竞猜总条数</span><strong>${records.length}</strong></div><div><span>预测正确</span><strong>${correct}</strong></div><div><span>预测准确率</span><strong>${rate}%</strong></div><div><span>最终积分</span><strong>${current}</strong></div></div><div class="section-title"><h2>全部竞猜历史</h2><span>积分统一显示为整数</span></div><div class="profile-history safe-history">${records.map(r=>`<article><div><small>${escapeHTML(r.created_at||'日期待确认')}</small><h3>${escapeHTML(matchName(r))}</h3><small>${escapeHTML(r.score||'比分待确认')}</small></div><span>${escapeHTML(r.prediction)}</span><span>权重 ${r.weight??'—'} · 置信度 ${r.confidence_percent??'—'}%</span><b class="prediction-result ${escapeHTML(r.result)}">${interactionResultLabel(r.result)}</b><strong class="points-change ${r.points_change>0?'positive':r.points_change<0?'negative':''}">${r.points_change>0?'+':''}${Math.round(r.points_change)}</strong><strong>${Math.round(r.total_points)}</strong></article>`).join('')||emptyState('暂无竞猜记录')}</div></div>`}

async function loadStoredData(rerender=false){try{const response=await fetch(`data/matches.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);matches=await response.json();if(rerender)home()}catch(error){app.innerHTML=emptyState('比赛数据读取失败：'+error.message)}}
async function loadPlayers(){try{const response=await fetch(`data/players.json?v=${Date.now()}`,{cache:'no-store'});players=response.ok?await response.json():[]}catch{players=[]}}
async function loadInteractions(){try{const response=await fetch(`data/interactions.json?v=${Date.now()}`,{cache:'no-store'});interactions=response.ok?await response.json():[]}catch{interactions=[]}}
async function loadApiData(){const source=document.querySelector('#dataSource');if(source)source.textContent='数据源：正在读取 football_api…';try{const response=await fetch(`${API_BASE_URL}/api/fixtures?league=1&season=2022`);if(!response.ok)throw new Error('接口返回 '+response.status);const payload=await response.json();if(payload.errors&&Object.keys(payload.errors).length)throw new Error(Object.values(payload.errors).join('；'));matches=payload.response.map(x=>({id:String(x.fixture.id),group:x.league.round||'世界杯',date:x.fixture.date.slice(0,10),time:new Date(x.fixture.date).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),home:x.teams.home.name,away:x.teams.away.name,score:x.goals.home==null?'—':`${x.goals.home}–${x.goals.away}`,status:x.fixture.status.long,venue:x.fixture.venue?.name||'—'}));activeView='all';home();document.querySelector('#sourceSelect').value='football_api';document.querySelector('#dataSource').textContent='数据源：football_api（2022）'}catch(error){if(source)source.textContent='football_api 读取失败：'+error.message}}
function parseRoute(){const route=location.hash.replace('#','')||'/world-cup/groups';if(route.startsWith('/matches/'))return {type:'match',id:decodeURIComponent(route.split('/').pop())};if(route.startsWith('/profiles/'))return {type:'profile',id:decodeURIComponent(route.split('/').pop())};if(route==='/login')return {type:'v3',view:'login'};if(route==='/my-predictions')return {type:'v3',view:'predictions'};if(route==='/leaderboard')return {type:'v3',view:'leaderboard'};if(route==='/admin')return {type:'v3',view:'admin'};if(route==='/change-password')return {type:'v3',view:'password'};const view=route.split('/').pop();return {type:'home',view:['groups','bracket','all','interactions'].includes(view)?view:'groups'}}
async function router(){const route=parseRoute();if(route.type==='home')activeView=route.view;if(!matches.length)await Promise.all([loadStoredData(),loadPlayers(),loadInteractions()]);if(route.type==='v3'&&window.renderV3Route){window.renderV3Route(route.view)}else if(route.type==='match'){detail(route.id)}else if(route.type==='profile'){profilePage(route.id)}else{home()}if(window.refreshAuthTools)window.refreshAuthTools();scrollTo(0,0)}
document.querySelector('#themeButton').onclick=()=>document.body.classList.toggle('dark');window.addEventListener('hashchange',router);router();
