// 部署 Worker 后，把这里改成 Worker 地址；留空时使用同域 /api 路径。
const API_BASE_URL='https://world-cup-api-proxy.zhanghao19900118.workers.dev';
const teams={ARG:['阿根廷','🇦🇷'],ESP:['西班牙','🇪🇸'],FRA:['法国','🇫🇷'],BRA:['巴西','🇧🇷'],ENG:['英格兰','🏴'],POR:['葡萄牙','🇵🇹'],GER:['德国','🇩🇪'],NED:['荷兰','🇳🇱'],JPN:['日本','🇯🇵'],USA:['美国','🇺🇸'],MEX:['墨西哥','🇲🇽'],CAN:['加拿大','🇨🇦']};
let matches=[
 {id:'m01',group:'A组',date:'2026-06-11',time:'15:00',home:'MEX',away:'CAN',score:'—',status:'未开始',venue:'墨西哥城体育场'},
 {id:'m02',group:'B组',date:'2026-06-11',time:'18:00',home:'USA',away:'JPN',score:'—',status:'未开始',venue:'洛杉矶体育场'},
 {id:'m03',group:'C组',date:'2026-06-12',time:'15:00',home:'ARG',away:'ESP',score:'—',status:'未开始',venue:'迈阿密体育场'},
 {id:'m04',group:'D组',date:'2026-06-12',time:'20:00',home:'FRA',away:'BRA',score:'—',status:'未开始',venue:'纽约新泽西体育场'},
 {id:'m05',group:'E组',date:'2026-06-13',time:'14:00',home:'ENG',away:'POR',score:'—',status:'未开始',venue:'多伦多体育场'},
 {id:'m06',group:'F组',date:'2026-06-13',time:'19:00',home:'GER',away:'NED',score:'—',status:'未开始',venue:'温哥华体育场'}
];
const bracket=[
 {round:'16 强',games:[['ARG','JPN','2–0'],['ESP','CAN','3–1'],['FRA','NED','2–1'],['BRA','USA','1–0']]},
 {round:'四分之一决赛',games:[['ARG','ESP','2–1'],['FRA','BRA','1–1']]},
 {round:'半决赛',games:[['ARG','FRA','—']]},
 {round:'决赛',games:[['胜者 SF1','胜者 SF2','—']]}
];
const histories={ARG:[['2026-06-03','智利','2–0','W','6–3 · 14–8 · 1.72'],['2026-05-29','乌拉圭','1–1','D','5–5 · 12–11 · 1.30'],['2026-03-26','哥伦比亚','3–1','W','7–2 · 16–7 · 2.18'],['2026-03-21','巴拉圭','1–0','W','4–4 · 11–9 · 暂无数据'],['2025-11-18','秘鲁','2–0','W','8–1 · 18–5 · 2.04']],ESP:[['2026-06-04','意大利','2–1','W','7–4 · 15–10 · 1.91'],['2026-05-30','比利时','0–0','D','6–3 · 13–8 · 1.43'],['2026-03-27','克罗地亚','1–2','L','5–6 · 12–14 · 1.22'],['2026-03-22','瑞士','3–0','W','9–2 · 19–6 · 2.61'],['2025-11-19','丹麦','2–0','W','6–4 · 14–7 · 暂无数据']]};
const players=[
 ['J. Álvarez','ARG','前锋',5,14,7,'2.10',3,1,0,'左脚 · 运动战 · 禁区内'],['L. Messi','ARG','前锋',4,12,6,'1.84',1,0,0,'左脚 · 任意球 · 禁区外'],['E. Fernández','ARG','中场',5,7,3,'0.68',12,2,0,'右脚 · 运动战 · 禁区外'],['Pedri','ESP','中场',5,8,4,'0.91',9,1,0,'右脚 · 运动战 · 禁区内'],['L. Yamal','ESP','前锋',5,16,8,'2.24',5,1,0,'左脚 · 反击 · 禁区内'],['Rodri','ESP','中场',4,5,2,'0.42',14,2,0,'暂无进球记录']
];
const app=document.querySelector('#app');
function flag(code){return teams[code]?.[1]||'◌'} function name(code){return teams[code]?.[0]||code}
function go(id){location.hash=`/matches/${id}`}
function matchCard(m){return `<article class="match-card" onclick="go('${m.id}')"><div class="match-top"><span>${m.group} · ${m.date}</span><span class="status upcoming">${m.status}</span></div><div class="team-line"><span class="flag">${flag(m.home)}</span><span>${name(m.home)}</span><b class="score">${m.score==='—'?'':m.score.split('–')[0]}</b></div><div class="team-line"><span class="flag">${flag(m.away)}</span><span>${name(m.away)}</span><b class="score">${m.score==='—'?'':m.score.split('–')[1]}</b></div><div class="match-foot"><span>${m.time} EDT</span><span>${m.venue} →</span></div></article>`}
function bracketHTML(){return `<div class="bracket-shell"><div class="bracket-toolbar"><div class="route-pills"><button class="route-pill active" data-team="ALL">全部路径</button>${['ARG','ESP','FRA','BRA'].map(t=>`<button class="route-pill" data-team="${t}">${flag(t)} ${name(t)}</button>`).join('')}</div><div class="zoom-controls"><button id="zoomOut">−</button><button id="zoomIn">＋</button></div></div><div class="bracket" id="bracket">${bracket.map((r,ri)=>`<section class="round"><h3>${r.round}</h3><div class="round-list">${r.games.map((g,gi)=>`<article class="bracket-card" data-teams="${g[0]} ${g[1]}" onclick="go('${ri===2?'m03':'m0'+(gi+3)}')"><div class="mini-team"><span class="name"><b>${flag(g[0])}</b>${name(g[0])}</span><strong>${g[2]==='—'?'':g[2].split('–')[0]}</strong></div><div class="mini-team"><span class="name"><b>${flag(g[1])}</b>${name(g[1])}</span><strong>${g[2]==='—'?'':g[2].split('–')[1]}</strong></div></article>`).join('')}</div></section>`).join('')}</div></div>`}
function home(){app.innerHTML=`<section class="hero"><div class="eyebrow">FIFA World Cup 2026</div><h1>一张图，看懂<br><em>每一次晋级。</em></h1><div class="hero-meta"><span><strong>48</strong> 支球队</span><span><strong>104</strong> 场比赛</span><span><strong>16</strong> 座主办城市</span><span>当地时区 <strong>EDT · 多伦多</strong></span></div></section><div class="container"><div class="control-row"><div class="segmented"><button class="active" data-view="all">全部赛程</button><button data-view="groups">小组赛</button><button data-view="bracket">淘汰赛</button></div><div class="filters"><select class="select" id="dateFilter"><option value="all">全部日期</option><option>2026-06-11</option><option>2026-06-12</option><option>2026-06-13</option></select><label class="source-control">数据源 <select class="select" id="sourceSelect"><option value="manual">手动（matches.json）</option><option value="football_api">football_api（2022）</option></select></label></div></div><div id="schedule"><div class="section-title"><h2>比赛赛程</h2><span>按当地时间排序 · 点击比赛查看详情</span></div><div class="match-grid" id="matchGrid">${matches.map(matchCard).join('')}</div><div class="section-title"><h2>淘汰赛晋级图</h2><span>点击球队可高亮晋级路线</span></div>${bracketHTML()}</div><div class="data-note"><span id="dataSource">数据源：正在读取 data/matches.json…</span><span id="updatedAt">最后更新：—</span></div></div>`; bindHome()}
function bindHome(){
  document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{
    document.querySelectorAll('[data-view]').forEach(item=>item.classList.remove('active'));
    button.classList.add('active');
    const grid=document.querySelector('.match-grid')?.parentElement;
    const bracketTitle=document.querySelector('.bracket-shell')?.previousElementSibling;
    const bracketShell=document.querySelector('.bracket-shell');
    if(button.dataset.view==='groups'){grid.style.display='block';bracketTitle.style.display='none';bracketShell.style.display='none'}
    else if(button.dataset.view==='bracket'){grid.style.display='none';bracketTitle.style.display='flex';bracketShell.style.display='block'}
    else{grid.style.display='block';bracketTitle.style.display='flex';bracketShell.style.display='block'}
  });
  document.querySelector('#dateFilter').onchange=event=>{
    document.querySelector('#matchGrid').innerHTML=matches.filter(match=>event.target.value==='all'||match.date===event.target.value).map(matchCard).join('')||'<p>该日期暂无比赛</p>';
  };
  document.querySelector('#sourceSelect').onchange=event=>event.target.value==='football_api'?refreshLiveData():loadStoredData();
  let zoom=1;
  const bracket=document.querySelector('#bracket');
  document.querySelector('#zoomIn').onclick=()=>{zoom=Math.min(1.25,zoom+.1);bracket.style.transform=`scale(${zoom})`};
  document.querySelector('#zoomOut').onclick=()=>{zoom=Math.max(.75,zoom-.1);bracket.style.transform=`scale(${zoom})`};
  document.querySelectorAll('.route-pill').forEach(pill=>pill.onclick=()=>{
    document.querySelectorAll('.route-pill').forEach(item=>item.classList.remove('active'));
    pill.classList.add('active');
    document.querySelectorAll('.bracket-card').forEach(card=>card.classList.toggle('highlight',pill.dataset.team!=='ALL'&&card.dataset.teams.includes(pill.dataset.team)));
  });
  loadStoredData();
}
async function refreshLiveData(){const select=document.querySelector('#sourceSelect');if(select)select.disabled=true;document.querySelector('#dataSource').textContent='数据源：正在读取 football_api…';try{const response=await fetch(`${API_BASE_URL}/api/fixtures?league=1&season=2022`,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('接口返回 '+response.status);const payload=await response.json();if(payload.errors&&Object.keys(payload.errors).length)throw new Error(Object.values(payload.errors).join('；'));if(!Array.isArray(payload.response))throw new Error('数据格式不正确');const live=payload.response.map(x=>({id:String(x.fixture?.id||x.fixture?.date),group:x.league?.round||'世界杯',date:(x.fixture?.date||'').slice(0,10),time:new Date(x.fixture?.date||Date.now()).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),homeCode:x.teams?.home?.code,awayCode:x.teams?.away?.code,home:x.teams?.home?.name||'主队',away:x.teams?.away?.name||'客队',score:x.goals?.home==null?'—':`${x.goals.home}–${x.goals.away}`,status:x.fixture?.status?.long||'未知',venue:x.fixture?.venue?.name||'—'}));if(!live.length)throw new Error('接口没有返回比赛');matches=live;document.querySelector('#matchGrid').innerHTML=matches.map(matchCard).join('');document.querySelector('#dataSource').textContent='数据源：football_api（2022 赛季）';document.querySelector('#updatedAt').textContent='最后更新：'+new Date().toLocaleString('zh-CN')}catch(error){document.querySelector('#dataSource').textContent='football_api 读取失败：'+error.message;console.warn(error)}finally{if(select)select.disabled=false}}
function history(team){let rows=[...(histories[team]||histories.ARG),...histories[team]||[]].slice(0,10);return rows.map(r=>`<div class="history-row"><span>${r[0].slice(5)}</span><span class="history-opponent"><i class="result-badge ${r[3].toLowerCase()}">${r[3]}</i>${r[1]}</span><span class="history-score">${r[2]}<small>角球 · 射门 · xG ${r[4]}</small></span></div>`).join('')}
function comparison(){const rows=[['近10场胜率',70,60,'%'],['场均进球',2.1,1.8,''],['场均失球',.8,.9,''],['场均角球',5.8,6.1,''],['场均射门',14.2,15.4,''],['场均射正',5.9,6.2,''],['场均 xG',1.85,1.92,'']];return rows.map(r=>`<div class="comp-row"><strong>${r[1]}${r[3]}</strong><span class="bar"><i style="width:${r[1]/Math.max(r[1],r[2])*100}%"></i></span><span class="comp-label">${r[0]}</span><span class="bar right"><i style="width:${r[2]/Math.max(r[1],r[2])*100}%"></i></span><strong>${r[2]}${r[3]}</strong></div>`).join('')}
function playerRows(){return players.map((p,i)=>`<tr class="player-row" onclick="openPlayer(${i})"><td><span class="player-name"><i class="avatar">${p[0].split(' ').map(x=>x[0]).join('')}</i>${p[0]} · ${flag(p[1])}</span></td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td>${p[5]}</td><td>${p[6]}</td><td>${p[7]}</td><td>${p[8]}</td><td>${p[9]}</td></tr>`).join('')}
function detail(id){const m=matches.find(x=>x.id===id)||matches[2];app.innerHTML=`<section class="detail-hero"><a class="back-link" href="#/world-cup">← 返回赛程</a><div class="versus"><div class="team-head"><span class="big-flag">${flag(m.home)}</span><h1>${name(m.home)}</h1><p>${m.home}</p></div><div class="match-center"><strong>VS</strong><span>${m.status}</span></div><div class="team-head"><span class="big-flag">${flag(m.away)}</span><h1>${name(m.away)}</h1><p>${m.away}</p></div></div><div class="detail-meta"><span>${m.date} · ${m.time} EDT</span><span>${m.group}</span><span>${m.venue}</span></div></section><div class="container"><div class="detail-tabs"><button class="active">比赛概览</button><button>球队近况</button><button>球员数据</button><button>数据说明</button></div><div class="section-title"><h2>球队状态对比</h2><span>比赛开始前最近 10 场 FIFA 国家队比赛</span></div><section class="stat-panel"><div class="team-summary"><span class="flag">${flag(m.home)}</span><h3>${name(m.home)}</h3><div class="form"><i class="w">W</i><i class="w">W</i><i class="d">D</i><i class="w">W</i><i class="w">W</i></div></div><div class="comparison">${comparison()}</div><div class="team-summary"><span class="flag">${flag(m.away)}</span><h3>${name(m.away)}</h3><div class="form"><i class="w">W</i><i class="d">D</i><i class="l">L</i><i class="w">W</i><i class="w">W</i></div></div></section><div class="section-title"><h2>最近比赛</h2><span><label><input type="checkbox" checked> 包含友谊赛</label></span></div><div class="two-col"><article class="list-card"><div class="card-head"><h3>${flag(m.home)} ${name(m.home)}</h3><span>最近 10 场</span></div>${history(m.home)}</article><article class="list-card"><div class="card-head"><h3>${flag(m.away)} ${name(m.away)}</h3><span>最近 10 场</span></div>${history(m.away)}</article></div><article class="players-card"><div class="card-head"><h3>关键球员表现</h3><div class="table-tools"><select class="select" id="playerFilter"><option value="all">全部球员</option><option value="前锋">前锋</option><option value="中场">中场</option></select><select class="select" id="sortPlayers"><option value="4">按射门</option><option value="5">按射正</option><option value="7">按抢断</option></select></div></div><table class="player-table"><thead><tr><th>球员</th><th>位置</th><th>出场</th><th>射门</th><th>射正</th><th>xG</th><th>抢断</th><th>黄牌</th><th>红牌</th></tr></thead><tbody id="playerBody">${playerRows()}</tbody></table></article><div class="data-note"><span>数据源：产品原型演示数据 · “暂无数据”未计入平均值</span><span>统计截止：${m.date} 开赛前 · 有效 xG 样本 8/10</span></div></div><div class="modal" id="playerModal" onclick="if(event.target===this)this.classList.remove('open')"><div class="modal-card"><button class="modal-close" onclick="playerModal.classList.remove('open')">×</button><div id="modalContent"></div></div></div>`;bindDetail()}
function bindDetail(){document.querySelector('#playerFilter').onchange=e=>{document.querySelector('#playerBody').innerHTML=players.filter(p=>e.target.value==='all'||p[2]===e.target.value).map((p)=>{let i=players.indexOf(p);return `<tr class="player-row" onclick="openPlayer(${i})"><td><span class="player-name"><i class="avatar">${p[0][0]}</i>${p[0]} · ${flag(p[1])}</span></td><td>${p[2]}</td><td>${p[3]}</td><td>${p[4]}</td><td>${p[5]}</td><td>${p[6]}</td><td>${p[7]}</td><td>${p[8]}</td><td>${p[9]}</td></tr>`}).join('')};document.querySelector('#sortPlayers').onchange=e=>{players.sort((a,b)=>Number(b[e.target.value])-Number(a[e.target.value]));document.querySelector('#playerBody').innerHTML=playerRows()}}
function openPlayer(i){const p=players[i];document.querySelector('#modalContent').innerHTML=`<div class="eyebrow" style="color:var(--green)">${p[2]} · ${flag(p[1])} ${name(p[1])}</div><h2>${p[0]}</h2><p style="color:var(--muted)">最近 5 场国家队比赛 · ${p[3]} 次出场</p><div class="stat-panel" style="grid-template-columns:repeat(4,1fr);text-align:center;margin:22px 0"><div style="padding:18px"><b>${p[4]}</b><small style="display:block">射门</small></div><div style="padding:18px"><b>${p[5]}</b><small style="display:block">射正</small></div><div style="padding:18px"><b>${p[6]}</b><small style="display:block">xG</small></div><div style="padding:18px"><b>${p[7]}</b><small style="display:block">抢断</small></div></div><h4>进球方式</h4><p>${p[10]}</p><p class="data-note">点击遮罩区域关闭</p>`;document.querySelector('#playerModal').classList.add('open')}
function router(){const hash=location.hash.replace('#','')||'/world-cup';if(hash.startsWith('/matches/'))detail(hash.split('/').pop());else home();scrollTo(0,0)}
async function loadStoredData(){const source=document.querySelector('#dataSource');if(source)source.textContent='数据源：正在读取 data/matches.json…';try{const response=await fetch(`data/matches.json?v=${Date.now()}`,{cache:'no-store'});if(!response.ok)throw new Error('HTTP '+response.status);const stored=await response.json();if(!Array.isArray(stored)||!stored.length)throw new Error('文件中没有比赛数据');matches=stored;const grid=document.querySelector('#matchGrid');if(grid)grid.innerHTML=matches.map(matchCard).join('');if(source)source.textContent='数据源：手动（data/matches.json）';const updated=document.querySelector('#updatedAt');const stamp=stored[0]?.last_updated;if(updated)updated.textContent='最后更新：'+(stamp||new Date().toLocaleString('zh-CN'))}catch(error){if(source)source.textContent='matches.json 读取失败：'+error.message;console.warn(error)}}
document.querySelector('#themeButton').onclick=()=>document.body.classList.toggle('dark');window.addEventListener('hashchange',router);router();
